#!/usr/bin/env python3
import json
from datetime import datetime, timezone, date, timedelta
from pathlib import Path

# Registro verificado em páginas oficiais. O workflow mantém um arquivo histórico
# e publica o JSON diariamente. Acrescente novos eventos seguindo o mesmo modelo.
EVENTS = [
 {"name":"H2HC — Hackers to Hackers Conference","start":"2026-11-01","end":"2026-11-01","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"Ofensiva & Pesquisa","description":"Evento tradicional de pesquisa em segurança; data exata de 2026 ainda não confirmada.","url":"https://www.h2hc.com.br/","tentative":True},
 {"name":"BHack Conference","start":"2026-10-01","end":"2026-10-01","city":"Belo Horizonte - MG","country":"Brasil","format":"presencial","category":"Comunidade & Pesquisa","description":"Conferência técnica de Belo Horizonte; data exata de 2026 ainda não confirmada.","url":"https://bhack.com.br/","tentative":True},
 {"name":"BSides Porto Alegre","start":"2026-07-25","end":"2026-07-25","city":"Porto Alegre - RS","country":"Brasil","format":"presencial","category":"Comunidade","description":"Evento comunitário previsto para 2026; confirmação oficial pendente.","url":"https://bsidespoa.org/","tentative":True},
 {"name":"BSides Fortaleza","start":"2026-08-22","end":"2026-08-22","city":"Fortaleza - CE","country":"Brasil","format":"presencial","category":"Comunidade","description":"Evento comunitário previsto para agosto de 2026; data oficial pendente.","url":"https://bsides.org/","tentative":True},
 {"name":"ISACA São Paulo Summit","start":"2026-10-15","end":"2026-10-15","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"GRC & Auditoria","description":"Evento anual de governança, risco e auditoria; data de 2026 ainda não confirmada.","url":"https://www.isaca.org/chapters5/sao-paulo","tentative":True},
 {"name":"Roadsec 2026","start":"2026-10-20","end":"2026-10-20","city":"São Paulo e outras cidades","country":"Brasil","format":"presencial","category":"Hacker & Comunidade","description":"Festival de hacking e cultura digital; calendário de 2026 ainda não confirmado.","url":"https://roadsec.com.br/","tentative":True},
 {"name":"Oxum Sec","start":"2026-01-31","end":"2026-01-31","city":"Salvador - BA","country":"Brasil","format":"presencial","category":"Comunidade","description":"Evento comunitário de diversidade e segurança da informação em Salvador.","url":"https://axesec.cc/pages/oxum/"},
 {"name":"Dia da Internet Segura","start":"2026-02-10","end":"2026-02-11","city":"Múltiplas cidades","country":"Brasil","format":"híbrido","category":"Conscientização","description":"Iniciativa de conscientização, educação e boas práticas de segurança digital.","url":"https://www.diadainternetsegura.org.br"},
 {"name":"DICB 2026","start":"2026-02-26","end":"2026-02-27","city":"Porto Alegre - RS","country":"Brasil","format":"presencial","category":"Forense & Pesquisa","description":"Digital Investigation Conference Brazil, focada em forense e investigação cibernética.","url":"https://wbeducacional.ac-page.com/dicb-2026"},
 {"name":"Security Leaders Brasília","start":"2026-03-04","end":"2026-03-04","city":"Brasília - DF","country":"Brasil","format":"presencial","category":"Executivos & CISO","description":"Fórum regional para lideranças de segurança, compliance e regulação.","url":"https://securityleaders.com.br/eventos/security-leaders-brasilia-2026/"},
 {"name":"Hack in Cariri","start":"2026-03-07","end":"2026-03-07","city":"Juazeiro do Norte - CE","country":"Brasil","format":"presencial","category":"Comunidade","description":"Encontro comunitário de cibersegurança no Cariri.","url":"https://hackincariri.com.br"},
 {"name":"Febraban SEC","start":"2026-03-18","end":"2026-03-19","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"GRC & Financeiro","description":"Segurança, regulação, fraude e risco no setor financeiro brasileiro.","url":"https://febrabantech.febraban.org.br/febrabansec"},
 {"name":"SecOps Summit","start":"2026-03-18","end":"2026-03-20","city":"Porto Alegre - RS","country":"Brasil","format":"presencial","category":"Defesa & SOC","description":"SOC, resposta a incidentes, threat hunting e operações defensivas.","url":"https://www.secopssummit.com.br"},
 {"name":"Hacking na Web Day Brasília","start":"2026-03-21","end":"2026-03-21","city":"Brasília - DF","country":"Brasil","format":"presencial","category":"AppSec & Ofensiva","description":"Conteúdo técnico de AppSec e exploração de vulnerabilidades web.","url":"https://www.hackingnawebday.com"},
 {"name":"BSides Rio de Janeiro","start":"2026-03-28","end":"2026-03-28","city":"Rio de Janeiro - RJ","country":"Brasil","format":"presencial","category":"Comunidade","description":"Conferência comunitária com hacking, trilhas técnicas e networking.","url":"https://bsidesrj.com.br"},
 {"name":"Tosconf","start":"2026-03-28","end":"2026-03-28","city":"Campinas - SP","country":"Brasil","format":"presencial","category":"Pesquisa & Comunidade","description":"Conferência técnica do Laboratório Hacker de Campinas.","url":"https://tosconf.lhc.net.br"},
 {"name":"Security Leaders Rio de Janeiro","start":"2026-04-01","end":"2026-04-01","city":"Rio de Janeiro - RJ","country":"Brasil","format":"presencial","category":"Executivos & CISO","description":"Gestão de risco e networking para lideranças de segurança.","url":"https://securityleaders.com.br/eventos/security-leaders-rio-de-janeiro-2026/"},
 {"name":"0x3 Hacker Conference","start":"2026-04-11","end":"2026-04-11","city":"Maceió - AL","country":"Brasil","format":"presencial","category":"Hacker & Comunidade","description":"Conferência hacker comunitária em Alagoas.","url":"https://conference.oxehc.com.br"},
 {"name":"Security Leaders Cyber Arena","start":"2026-04-17","end":"2026-04-19","city":"Guarujá - SP","country":"Brasil","format":"presencial","category":"Executivos & CISO","description":"Imersão de três dias com CISOs e lideranças de segurança.","url":"https://securityleaders.com.br/eventos/security-leaders-cyber-arena-2026/"},
 {"name":"IAM Tech Day","start":"2026-04-22","end":"2026-04-23","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"IAM & Zero Trust","description":"Identidade, acesso, MFA, passkeys, governança e Zero Trust.","url":"https://iamtechday.org/eventos/iam-tech-day-sao-paulo-abril-2026/"},
 {"name":"BSides Floripa","start":"2026-04-25","end":"2026-04-25","city":"Florianópolis - SC","country":"Brasil","format":"presencial","category":"Comunidade","description":"Conferência comunitária BSides com trilhas e palestras técnicas.","url":"https://www.bsidesfloripa.org"},
 {"name":"CryptoRave","start":"2026-05-08","end":"2026-05-09","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"Privacidade & Criptografia","description":"Criptografia, privacidade, ativismo digital e cultura hacker.","url":"https://cryptorave.org"},
 {"name":"Security Leaders Belo Horizonte","start":"2026-05-12","end":"2026-05-12","city":"Belo Horizonte - MG","country":"Brasil","format":"presencial","category":"Executivos & CISO","description":"Estratégia e gestão de riscos para lideranças de segurança em Minas Gerais.","url":"https://securityleaders.com.br/eventos/security-leaders-belo-horizonte-2026/"},
 {"name":"Sirena Conference","start":"2026-05-14","end":"2026-05-14","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"Defesa & CTI","description":"Resposta a incidentes, inteligência de ameaças e defesa ativa.","url":"https://www.sirenaconference.com"},
 {"name":"You Sh0t the Sheriff (YSTS)","start":"2026-05-18","end":"2026-05-18","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"Executivos & Pesquisa","description":"Evento técnico e exclusivo por convite para especialistas e lideranças.","url":"https://www.ysts.org"},
 {"name":"Security Leaders Porto Alegre","start":"2026-05-27","end":"2026-05-27","city":"Porto Alegre - RS","country":"Brasil","format":"presencial","category":"Executivos & CISO","description":"Resiliência e estratégia para lideranças de cibersegurança da região Sul.","url":"https://securityleaders.com.br/eventos/security-leaders-porto-alegre-2026/"},
 {"name":"DunaSec","start":"2026-05-30","end":"2026-05-30","city":"Natal - RN","country":"Brasil","format":"presencial","category":"Comunidade","description":"Conferência para fortalecimento da comunidade potiguar de segurança.","url":"https://dunasec.com.br"},
 {"name":"BSides Recife","start":"2026-06-05","end":"2026-06-06","city":"Recife - PE","country":"Brasil","format":"presencial","category":"Comunidade","description":"Trilhas técnicas e comunidade de cibersegurança pernambucana.","url":"https://www.bsidesrecife.com.br"},
 {"name":"Security Leaders Curitiba","start":"2026-06-10","end":"2026-06-10","city":"Curitiba - PR","country":"Brasil","format":"presencial","category":"Executivos & CISO","description":"Riscos cibernéticos para indústria, agronegócio e tecnologia.","url":"https://securityleaders.com.br/eventos/security-leaders-curitiba-2026/"},
 {"name":"Security Leaders Floripa","start":"2026-06-17","end":"2026-06-17","city":"Florianópolis - SC","country":"Brasil","format":"presencial","category":"Executivos & CISO","description":"Estratégias de segurança para o polo tecnológico catarinense.","url":"https://securityleaders.com.br/eventos/security-leaders-florianopolis-2026/"},
 {"name":"BSides VIX","start":"2026-06-20","end":"2026-06-20","city":"Vitória - ES","country":"Brasil","format":"presencial","category":"Comunidade","description":"Encontro técnico da comunidade capixaba de segurança.","url":"http://bsides.vix.br"},
 {"name":"8.8 Brasil","start":"2026-06-26","end":"2026-06-27","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"Ofensiva & Pesquisa","description":"Pesquisa de vulnerabilidades e segurança ofensiva.","url":"https://8dot8.org"},
 {"name":"Cajusec Security Conference","start":"2026-07-11","end":"2026-07-11","city":"Aracaju - SE","country":"Brasil","format":"presencial","category":"Comunidade","description":"Evento sergipano com comunidade local e palestrantes nacionais.","url":"https://www.cajusec.com.br"},
 {"name":"Fórum Brasileiro de CSIRTs","start":"2026-07-28","end":"2026-07-30","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"CSIRT & Defesa","description":"Times de resposta, inteligência, coordenação nacional e Workshop MISP.","url":"https://forum.cert.br"},
 {"name":"Gartner Security & Risk Management Summit","start":"2026-08-04","end":"2026-08-05","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"Executivos & Risco","description":"Evento para CISOs e líderes de risco da América Latina.","url":"https://www.gartner.com/pt-br/conferences/la/security-risk-management-brazil"},
 {"name":"Security Leaders Recife","start":"2026-08-12","end":"2026-08-12","city":"Recife - PE","country":"Brasil","format":"presencial","category":"Executivos & CISO","description":"Fórum de lideranças e segurança no ecossistema de TI pernambucano.","url":"https://securityleaders.com.br"},
 {"name":"NullByte Security Conference","start":"2026-11-07","end":"2026-11-07","city":"Salvador - BA","country":"Brasil","format":"presencial","category":"Ofensiva & Pesquisa","description":"Conferência hacker de Salvador focada em pesquisa ofensiva.","url":"https://nullbyte-con.org/"},
 {"name":"FortalSec 2026","start":"2026-04-25","end":"2026-04-25","city":"Fortaleza - CE","country":"Brasil","format":"presencial","category":"Comunidade & CTF","description":"Evento regional com palestras, comunidade, exposição e competição CTF.","url":"https://www.fortalsec.com/"},
 {"name":"BSidesSP 2026","start":"2026-05-16","end":"2026-05-17","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"Comunidade & Ofensiva","description":"Conferência comunitária da rede Security BSides em São Paulo.","url":"https://bsides.org/event/bsidessp-5/"},
 {"name":"RSAC Conference 2026","start":"2026-03-23","end":"2026-03-26","city":"São Francisco, CA","country":"Estados Unidos","format":"presencial","category":"Mercado & Estratégia","description":"Conferência global para profissionais, lideranças, pesquisa e mercado de segurança.","url":"https://www.rsaconference.com/"},
 {"name":"Black Hat USA 2026","start":"2026-08-01","end":"2026-08-06","city":"Las Vegas, NV","country":"Estados Unidos","format":"presencial","category":"Ofensiva & Pesquisa","description":"Treinamentos, briefings técnicos e demonstrações de ferramentas de segurança.","url":"https://www.blackhat.com/"},
 {"name":"DEF CON 34","start":"2026-08-06","end":"2026-08-09","city":"Las Vegas, NV","country":"Estados Unidos","format":"presencial","category":"Comunidade & Hacker","description":"Grande encontro da comunidade hacker com villages, pesquisas, competições e CTFs.","url":"https://defcon.org/"},
 {"name":"SBSeg 2026","start":"2026-09-01","end":"2026-09-04","city":"Armação dos Búzios - RJ","country":"Brasil","format":"presencial","category":"Pesquisa & CTF","description":"Simpósio Brasileiro de Cibersegurança com sessões técnicas, minicursos, indústria e CTF.","url":"https://www.sbseg2026.uff.br/"},
 {"name":"CyberSecGo 2026","start":"2026-09-03","end":"2026-09-04","city":"Goiânia - GO","country":"Brasil","format":"presencial","category":"Defesa & Governança","description":"Trilhas técnica, governança e inovação para profissionais e lideranças de segurança.","url":"https://www.cybersecgo.com.br/"},
 {"name":"Billington CyberSecurity Summit","start":"2026-09-08","end":"2026-09-10","city":"Washington, DC","country":"Estados Unidos","format":"presencial","category":"Governo & Estratégia","description":"Encontro internacional focado em segurança nacional, governo e liderança cibernética.","url":"https://billingtoncybersummit.com/"},
 {"name":"Blue Team Con","start":"2026-09-10","end":"2026-09-13","city":"Chicago, IL","country":"Estados Unidos","format":"presencial","category":"Defesa","description":"Conferência dedicada a blue team, detecção, resposta e operações defensivas.","url":"https://blueteamcon.com/"},
 {"name":"Mind The Sec 2026","start":"2026-09-15","end":"2026-09-17","city":"São Paulo - SP","country":"Brasil","format":"híbrido","category":"Mercado & Técnica","description":"Grande encontro latino-americano de cybersecurity para especialistas, gestores e CISOs.","url":"https://www.mindthesec.com.br/"},
 {"name":"Cyber Security Summit Brasil","start":"2026-10-05","end":"2026-10-06","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"Executivos & CISO","description":"Lideranças de segurança, risco, tecnologia e governo discutem confiança digital e estratégia.","url":"https://cybersecuritysummit.com.br/"},
 {"name":"Futurecom 2026","start":"2026-10-06","end":"2026-10-08","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"Cloud, IA & Segurança","description":"Infraestrutura digital, cloud, segurança, soberania e regulação em um grande fórum de tecnologia.","url":"https://www.futurecom.com.br/"},
 {"name":"Black Hat Canada","start":"2026-10-06","end":"2026-10-08","city":"Toronto","country":"Canadá","format":"presencial","category":"Ofensiva & Pesquisa","description":"Briefings técnicos e pesquisa aplicada no formato internacional da Black Hat.","url":"https://www.blackhat.com/"},
 {"name":"European Cybersecurity Challenge","start":"2026-10-12","end":"2026-10-16","city":"Europa","country":"União Europeia","format":"presencial","category":"CTF & Talentos","description":"Competição europeia organizada pela ENISA para novos talentos em cibersegurança.","url":"https://ecsc.eu/"},
 {"name":"ISC2 Security Congress","start":"2026-10-19","end":"2026-10-22","city":"Nashville, TN","country":"Estados Unidos","format":"híbrido","category":"Profissionais & Carreira","description":"Conteúdo técnico e estratégico para profissionais certificados e líderes de segurança.","url":"https://www.isc2.org/congress"},
 {"name":"II CIGRE Security 2026","start":"2026-10-28","end":"2026-10-29","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"Infraestrutura Crítica","description":"Seminário técnico de cibersegurança para energia, automação e ambientes de missão crítica.","url":"https://ce-d2.cigre.org.br/"},
 {"name":"OWASP Global AppSec","start":"2026-11-03","end":"2026-11-05","city":"Estados Unidos","country":"Estados Unidos","format":"presencial","category":"AppSec","description":"Conferência global da OWASP dedicada à segurança de aplicações e software.","url":"https://owasp.org/events/"},
 {"name":"IT Summit Nacional 2026","start":"2026-11-10","end":"2026-11-10","city":"São Paulo - SP","country":"Brasil","format":"presencial","category":"TI & Cibersegurança","description":"Encontro B2B para líderes e especialistas de tecnologia e segurança.","url":"https://itsummit.com.br/"},
 {"name":"Black Hat Middle East & Africa","start":"2026-12-01","end":"2026-12-03","city":"Riad","country":"Arábia Saudita","format":"presencial","category":"Ofensiva & Pesquisa","description":"Conferência internacional com treinamentos, pesquisa, ferramentas e comunidade hacker.","url":"https://blackhatmea.com/"}
]

def main():
    confirmed = {"FortalSec 2026", "BSidesSP 2026", "BSides Recife", "BSides VIX", "Fórum Brasileiro de CSIRTs", "SBSeg 2026", "CyberSecGo 2026", "Mind The Sec 2026", "Cyber Security Summit Brasil", "Futurecom 2026", "II CIGRE Security 2026", "IT Summit Nacional 2026", "Billington CyberSecurity Summit", "Blue Team Con", "Black Hat Canada", "European Cybersecurity Challenge", "ISC2 Security Congress", "OWASP Global AppSec", "Black Hat Middle East & Africa"}
    archive_cutoff = date(2026, 1, 1)
    published = []
    for event in EVENTS:
        ending = date.fromisoformat(event.get("end") or event["start"])
        if ending >= archive_cutoff:
            item = dict(event)
            if item.get("tentative"):
                item["status"] = "NO RADAR"
            elif ending < date.today():
                item["status"] = "ENCERRADO" if item["name"] in confirmed else "ARQUIVO 2026"
            else:
                item["status"] = "CONFIRMADO" if item["name"] in confirmed else "DATA A CONFIRMAR"
            published.append(item)
    payload = {"updated_at": datetime.now(timezone.utc).isoformat(), "events": sorted(published, key=lambda x: x["start"])}
    out = Path("events.json")
    out.write_text(json.dumps(payload, ensure_ascii=False, indent=2)+"\n", encoding="utf-8")
    print(f"Publicados {len(published)} eventos entre agenda e arquivo")

if __name__ == "__main__": main()
